spring:
  application:
    name: "franquicias-api"
  data:
    mongodb:
      uri: "${MONGO_DB_URI}"
      username: "${MONGO_DB_USERNAME}"
      password: "${MONGO_DB_PASSWORD}"
      cluster-url: "${MONGO_DB_CLUSTER_URL}"
      database: "${MONGO_DB_DATABASE}"
server:
  port: 8080
api:
  base:
    path: "/api-franquicias"

